// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDARkgFNx__szOvoQnWr5Ul_SBgsYJ0Hrg',
    appId: '1:65014992500:web:5b15cdff2209d17b088b21',
    messagingSenderId: '65014992500',
    projectId: 'pokedexapp-bf513',
    authDomain: 'pokedexapp-bf513.firebaseapp.com',
    storageBucket: 'pokedexapp-bf513.firebasestorage.app',
    measurementId: 'G-PXQGEXNGXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYN_oIAdXgC8bF_Mhw5joZLNi3b7zUSmI',
    appId: '1:65014992500:android:1485cf0a911f014f088b21',
    messagingSenderId: '65014992500',
    projectId: 'pokedexapp-bf513',
    storageBucket: 'pokedexapp-bf513.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM59jyUThqYnDj4fGMOSBGkeqZHPUcJ9w',
    appId: '1:65014992500:ios:ef39f8fbb4f6e725088b21',
    messagingSenderId: '65014992500',
    projectId: 'pokedexapp-bf513',
    storageBucket: 'pokedexapp-bf513.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM59jyUThqYnDj4fGMOSBGkeqZHPUcJ9w',
    appId: '1:65014992500:ios:ef39f8fbb4f6e725088b21',
    messagingSenderId: '65014992500',
    projectId: 'pokedexapp-bf513',
    storageBucket: 'pokedexapp-bf513.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDARkgFNx__szOvoQnWr5Ul_SBgsYJ0Hrg',
    appId: '1:65014992500:web:9f6f67644c4ca4c5088b21',
    messagingSenderId: '65014992500',
    projectId: 'pokedexapp-bf513',
    authDomain: 'pokedexapp-bf513.firebaseapp.com',
    storageBucket: 'pokedexapp-bf513.firebasestorage.app',
    measurementId: 'G-7D1T8CTNPW',
  );
}
